#!/usr/bin/env bash
# Generated by `crane_tag` (//oci:crane_tag.bzl). Tags one digest with every
# tag in the expanded list. Idempotent: re-tagging a digest with the same tag
# is a no-op at the registry.

# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---

set -o errexit -o nounset -o pipefail

# CRANE may be overridden from the environment; the tests point it at a fake
# that records the commands.
readonly CRANE="${CRANE:-$(rlocation "{{crane_rlocation}}")}"
DIGEST_FILE=$(rlocation "{{digest_rlocation}}")
TAGS_FILE=$(rlocation "{{tags_rlocation}}")
readonly DIGEST_FILE TAGS_FILE
readonly REPOSITORY="{{repository}}"

DIGEST=$(cat "${DIGEST_FILE}")
readonly DIGEST

while IFS= read -r TAG; do
  [[ -n "${TAG}" ]] || continue
  echo "crane tag ${REPOSITORY}@${DIGEST} ${TAG}" >&2
  "${CRANE}" tag "${REPOSITORY}@${DIGEST}" "${TAG}"
done < "${TAGS_FILE}"
