#!/usr/bin/env bash
# Generated by `crane_tag` (//oci:crane_tag.bzl). Tags one digest with every
# tag in the expanded list. Idempotent: re-tagging a digest with the same tag
# is a no-op at the registry.
set -o errexit -o nounset -o pipefail

# Resolve paths against the runfiles tree whether invoked via `bazel run` or
# directly as a test data dependency.
RUNFILES="${RUNFILES_DIR:-${BASH_SOURCE[0]}.runfiles}"
if [[ -d "${RUNFILES}/_main" ]]; then
  cd "${RUNFILES}/_main"
fi

readonly CRANE="${CRANE:-{{crane_path}}}"
readonly DIGEST_FILE="{{digest_file}}"
readonly TAGS_FILE="{{tags_file}}"
readonly REPOSITORY="{{repository}}"

DIGEST=$(cat "${DIGEST_FILE}")
readonly DIGEST

while IFS= read -r TAG; do
  [[ -n "${TAG}" ]] || continue
  echo "crane tag ${REPOSITORY}@${DIGEST} ${TAG}" >&2
  "${CRANE}" tag "${REPOSITORY}@${DIGEST}" "${TAG}"
done < "${TAGS_FILE}"
