#!/usr/bin/env bash

# After adding a new third-party dependency, developers should run this script.
set -o errexit -o nounset -o pipefail

SCRIPT_DIR="$(realpath "$(dirname "$0")")"

bazel run @multitool//tools/multitool -- --lockfile="$SCRIPT_DIR/tools.lock.json" update
